FROM registry.gitlab.com/simpleworks-gmbh/staf-environment:latest

###
## Install needed software
#

# refresh package list
RUN apt update -y

# install java openjdk 8
RUN apt install openjdk-8-jdk -y

# install unzip
RUN apt install unzip -y

# install wget
RUN apt install wget -y 

# fetch maven-3.8.8
RUN wget https://dlcdn.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip

# unzip maven-3.8.8
RUN unzip apache-maven-3.8.8-bin.zip

RUN mv apache-maven-3.8.8 /opt/maven

# Set mvn environment variables
ENV M2_HOME=/opt/maven
ENV MAVEN_HOME=/opt/maven
ENV PATH=${M2_HOME}/bin:${PATH}

###
## configure software build
#

# copy work directory to mount point
COPY . /mnt
# setting working directory
WORKDIR /mnt

# compile software
RUN mvn clean install