FROM registry.gitlab.com/simpleworks-gmbh/staf-environment:latest

###
## configure software build
#

# copy work directory to mount point
COPY . /mnt
# setting working directory
WORKDIR /mnt

# compile software
RUN mvn clean install