blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/simpleworks-gmbh/staf/blob/main/README.md
    about: Please take a look into the documentation, before you open any issue.