name: staf publish to maven central workflow
on:
  release:
    types: [published]
    branch: master
    tags:
        - 'v*'

jobs:
  fetch-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tagName.outputs.tag }}
    steps:  
    - uses: olegtarasov/get-tag@v2.1
      id: tagName
 
  publish-to-maven-central:
    runs-on: ubuntu-latest
    needs: fetch-tag 
    container:
      image: registry.gitlab.com/simpleworks-gmbh/staf/image:${{ needs.fetch-tag.outputs.tag }}
      options: --user root
      credentials:
        username: ${{ secrets.GITLAB_USERNAME }}
        password: ${{ secrets.GITLAB_ACCCESS_TOKEN }}
        
    steps: 
      - name: Publish package 
        run:  mvn -Pci-cd -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -Did.username=${{ secrets.OSSRH_USERNAME }} -Did.password=${{ secrets.OSSRH_TOKEN }} -DaltDeploymentRepository=${{ secrets.NEXUS_URL }} javadoc:jar source:jar deploy
        working-directory: /mnt
        env:
          HOME: /root
      - name: notify slack channel 
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/simpleworks-gmbh.png?size=48
          SLACK_MESSAGE:  |
             ${{ github.repository }} ${{ steps.tagName.outputs.tag }} has been deployed to <https://s01.oss.sonatype.org/#stagingRepositories|Nexus> :champagne:
          SLACK_TITLE:  ${{ github.repository }}
          SLACK_USERNAME: incoming-webhook
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: notify slack channel 
        uses: rtCamp/action-slack-notify@v2
        if:  success() != true
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/simpleworks-gmbh.png?size=48
          SLACK_MESSAGE:  |
             the `${{ github.job }}` job  <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|has failed unfortunately> :cry:
          SLACK_TITLE:  ${{ github.repository }}
          SLACK_USERNAME: incoming-webhook
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
